# Generated by Django 2.1.2 on 2018-10-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_auto_20181015_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image2',
            field=models.ImageField(default='images/default-01.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='image3',
            field=models.ImageField(default='images/default-01.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='image4',
            field=models.ImageField(default='images/default-01.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='image5',
            field=models.ImageField(default='images/default-01.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='image6',
            field=models.ImageField(default='images/default-01.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='image7',
            field=models.ImageField(default='images/default-01.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='image8',
            field=models.ImageField(default='images/default-01.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='image9',
            field=models.ImageField(default='images/default-01.png', upload_to='images/'),
        ),
    ]
