# Generated by Django 2.1.2 on 2018-10-15 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181011_0353'),
        ('blog', '0002_auto_20181015_1647'),
    ]

    operations = [
    ]
